version: '3.7'

services:
  api:
    image: api
    restart: on-failure
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./media:/project/media
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api